#ifndef PROTOCOL_H
#define PROTOCOL_H

#include <stdlib.h>
#include <string.h>
//#include <unistd.h>

enum ENUM_MSG_TYPE{

    ENUM_MSG_TYPE_MIN = 0,

    ENUM_MSG_TYPE_REGIST_REQUEST,
    ENUM_MSG_TYPE_REGIST_RESPOND,

    ENUM_MSG_TYPE_LOGIN_REQUEST,
    ENUM_MSG_TYPE_LOGIN_RESPOND,

    ENUM_MSG_TYPE_LOGIN_OUT_REQUEST,
    ENUM_MSG_TYPE_LOGIN_OUT_RESPOND,

    ENUM_MSG_TYPE_ALL_ONLINE_REQUEST,
    ENUM_MSG_TYPE_ALL_ONLINE_RESPOND,

    ENUM_MSG_TYPE_SEARCH_USR_REQUEST,
    ENUM_MSG_TYPE_SEARCH_USR_RESPOND,

    ENUM_MSG_TYPE_ADD_FRIEND_REQUEST,
    ENUM_MSG_TYPE_ADD_FRIEND_RESPOND,
    ENUM_MSG_TYPE_ADD_FRIEND_AGREE,
    ENUM_MSG_TYPE_ADD_FRIEND_REFUSE,
    ENUM_MSG_TYPE_FLUSH_FRIEND_REQUEST,
    ENUM_MSG_TYPE_FLUSH_FRIEND_RESPOND,
    ENUM_MSG_TYPE_DELETE_FRIEND_REQUEST,
    ENUM_MSG_TYPE_DELETE_FRIEND_RESPOND,

    ENUM_MSG_TYPE_PRIVATE_CHAT_REQUEST,
    ENUM_MSG_TYPE_PRIVATE_CHAT_RESPOND,
    ENUM_MSG_TYPE_GROUP_CHAT_REQUEST,
    ENUM_MSG_TYPE_GROUP_CHAT_RESPOND,

    ENUM_MSG_TYPE_CREATE_DIR_REQUEST,
    ENUM_MSG_TYPE_CREATE_DIR_RESPOND,
    ENUM_MSG_TYPE_FLUSH_FILE_REQUEST,
    ENUM_MSG_TYPE_FLUSH_FILE_RESPOND,
    ENUM_MSG_TYPE_DELETE_DIR_FILE_REQUEST,
    ENUM_MSG_TYPE_DELETE_DIR_FILE_RESPOND,
    ENUM_MSG_TYPE_RENAME_DIR_FILE_REQUEST,
    ENUM_MSG_TYPE_RENAME_DIR_FILE_RESPOND,
    ENUM_MSG_TYPE_ENTER_DIR_REQUEST,
    ENUM_MSG_TYPE_ENTER_DIR_RESPOND,
    ENUM_MSG_TYPE_UPLOAD_REQUEST,
    ENUM_MSG_TYPE_UPLOAD_PROCESS,
    ENUM_MSG_TYPE_UPLOAD_FINISH,
    ENUM_MSG_TYPE_DOWNLOAD_REQUEST,
    ENUM_MSG_TYPE_DOWNLOAD_RESPOND,
    ENUM_MSG_TYPE_DOWNLOAD_PROCESS,
    ENUM_MSG_TYPE_DOWNLOAD_FINISH,
    ENUM_MSG_TYPE_DOWNLOAD_ERROR,
    ENUM_MSG_TYPE_FILE_SHARE_REQUEST,
    ENUM_MSG_TYPE_FILE_SHARE_RESPOND,
    ENUM_MSG_TYPE_FILE_SHARE_INFORM,
    ENUM_MSG_TYPE_FILE_SHARE_CONFIRM,
    ENUM_MSG_TYPE_FILE_SHARE_DONE,
    ENUM_MSG_TYPE_UPLOAD_CANCEL_REQUEST,
    ENUM_MSG_TYPE_DOWNLOAD_CANCEL_REQUEST,
    ENUM_MSG_TYPE_MAX = 0xffffffff
};

struct FileInfo{

    char fileName[64];
    int fileType;
};


struct PDU
{
    unsigned int uiPDUlen;      //总的大小
    unsigned int uiMsgType;     //消息类型
    unsigned int uiMsglen;      //消息长度
    char caData[64];
    int caMsg[];                //实际消息

};

PDU* makePDU(unsigned int uiMsglen = 0);        //需要传递caMsg数组的大小

#endif // PROTOCOL_H
